### ISSUE TITLE
Roadmap to Beta

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#381]
(updated June 5th) 

Maybe it makes sense to use the move to the scoped NPM packages to also move to a move reliable compiler? From your point of view, are there issues left that need to be addressed before we go into beta? 

What about proceeding in this order:

- [x] when returning from his vacation, @hkollmann creates a legacy branch which will be used to publish a final version of `qooxdoo-compiler` with a deprecation notice
- [x] rebase & merge of @hkollmann's #373. This will first move to the package to `@qooxdoo/compiler` 
- [x] rebase & merge of my #380, which renames contrib -> package . It produces a user code base that is backwards-incompatible with earlier versions of the compiler, but that's ok if it is a based on a new package name. 
- [x] rebase & merge of @oetiker's #365, which should get an option to be really strict (e.g. for testing) and throw on a failed schema validation.
- [x] increase the version to "1.0.0.-beta-*" 
- [x] add migration code that updates the `@qooxdoo/compiler` dependency in the user code
- [x] move documentation from https://oetiker.github.io/qooxdoo-docs to qooxdoo repo
- [ ] @johnspackman fixes the most important bugs on his list 
- [x] update build scripts to copy documentation to subfolder of the qooxdoo website and to build demoapps from `qxl.*` repos
- [x] finish updating documentation, merge compiler documentation, remove it from compiler repo
- [ ] move old website to subfolder of the website and replace with new "docsify"-based website
- [ ] write blog post announcing beta

**Comment by cboulanger** [comment]
And, as mentioned in the title of the issue, we could then try to reach beta status as soon as possible, to give users a sense of trust that we won't radically alter the compiler before release again.

**Comment by hkollmann** [comment]
Should we move the qooxdoo package to 6.0.0-beta too? Releasing the new npm package would be a good oppertunity.

**Comment by cboulanger** [comment]
@hkollmann Maybe this should be discussed in a dedicated issue in the qooxdoo repo. In my opinion, we should assign all open issues that need to be addressed before release to https://github.com/qooxdoo/qooxdoo/milestone/65 and then determine if there are issues left that would block beta status.

**Comment by cboulanger** [comment]
Updated description to include @johnspackman's suggestion here: https://github.com/qooxdoo/qooxdoo-compiler/pull/380#issuecomment-487479798

**Comment by oetiker** [comment]
regarding the name how if we also went to 6.0.0-beta ?

**Comment by cboulanger** [comment]
@oetiker I'd say as long as the compiler is developed outside of the framework code, I'd keep the versions different - since the release cycle is different, it seems to me that visibly different version numbers are better.
